
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.101.9:3306/ngx-admin?serverTimezone=GMT%2B8&nullNamePatternMatchesAll=true
    username: root
    password: root

  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
     database : MYSQL
     show-sql : false
     hibernate:
       ddl-auto : update
       naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
     properties:
       hibernate:
         dialect : org.hibernate.dialect.MySQL5InnoDBDialect


security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data